apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: ai-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.10.1
          ports:
            - containerPort: 6333
