apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfuse
  namespace: observability-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langfuse
  template:
    metadata:
      labels:
        app: langfuse
    spec:
      containers:
        - name: langfuse
          image: ghcr.io/langfuse/langfuse:2.93.0
          ports:
            - containerPort: 3000
            - containerPort: 4317
