apiVersion: v1
kind: Service
metadata:
  name: langfuse
  namespace: observability-system
spec:
  selector:
    app: langfuse
  ports:
    - name: ui
      port: 3000
      targetPort: 3000
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
